# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voteUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1138, 766)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/vote/image/star-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(25, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_windowStatus = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_windowStatus.sizePolicy().hasHeightForWidth())
        self.pushButton_windowStatus.setSizePolicy(sizePolicy)
        self.pushButton_windowStatus.setMinimumSize(QtCore.QSize(30, 40))
        self.pushButton_windowStatus.setMaximumSize(QtCore.QSize(30, 40))
        self.pushButton_windowStatus.setStyleSheet("#pushButton_windowStatus{\n"
"    \n"
"    border-image: url(:/vote/image/fullscreen.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_windowStatus:hover\n"
"{\n"
"    \n"
"    border-image: url(:/vote/image/fullscreen-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_windowStatus:pressed\n"
"{\n"
"    border-image: url(:/vote/image/fullscreen-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_windowStatus.setText("")
        self.pushButton_windowStatus.setCheckable(True)
        self.pushButton_windowStatus.setObjectName("pushButton_windowStatus")
        self.gridLayout_2.addWidget(self.pushButton_windowStatus, 1, 2, 1, 1)
        self.pushButton_down_font_size = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_down_font_size.sizePolicy().hasHeightForWidth())
        self.pushButton_down_font_size.setSizePolicy(sizePolicy)
        self.pushButton_down_font_size.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_down_font_size.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_down_font_size.setStyleSheet("#pushButton_down_font_size{\n"
"    border-image: url(:/vote/image/font_size_down.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_down_font_size:hover\n"
"{\n"
"    border-image: url(:/vote/image/font_size_down_press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_down_font_size:pressed\n"
"{\n"
"    border-image: url(:/vote/image/font_size_down_press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_down_font_size.setText("")
        self.pushButton_down_font_size.setObjectName("pushButton_down_font_size")
        self.gridLayout_2.addWidget(self.pushButton_down_font_size, 12, 2, 1, 1)
        self.pushButton_delCol = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delCol.sizePolicy().hasHeightForWidth())
        self.pushButton_delCol.setSizePolicy(sizePolicy)
        self.pushButton_delCol.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_delCol.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_delCol.setStyleSheet("#pushButton_delCol{\n"
"    border-image: url(:/vote/image/减号.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_delCol:hover\n"
"{\n"
"    border-image: url(:/vote/image/减号-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_delCol:pressed\n"
"{\n"
"    border-image: url(:/vote/image/减号-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_delCol.setText("")
        self.pushButton_delCol.setObjectName("pushButton_delCol")
        self.gridLayout_2.addWidget(self.pushButton_delCol, 9, 2, 1, 1)
        self.pushButton_addCol = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addCol.sizePolicy().hasHeightForWidth())
        self.pushButton_addCol.setSizePolicy(sizePolicy)
        self.pushButton_addCol.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_addCol.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_addCol.setStyleSheet("#pushButton_addCol{\n"
"    border-image: url(:/vote/image/加.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_addCol:hover\n"
"{\n"
"    border-image: url(:/vote/image/加-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_addCol:pressed\n"
"{\n"
"    border-image: url(:/vote/image/加-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_addCol.setText("")
        self.pushButton_addCol.setObjectName("pushButton_addCol")
        self.gridLayout_2.addWidget(self.pushButton_addCol, 8, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.widget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 6, 2, 1, 1)
        self.pushButton_menu = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_menu.sizePolicy().hasHeightForWidth())
        self.pushButton_menu.setSizePolicy(sizePolicy)
        self.pushButton_menu.setMinimumSize(QtCore.QSize(30, 40))
        self.pushButton_menu.setMaximumSize(QtCore.QSize(30, 40))
        self.pushButton_menu.setStyleSheet("#pushButton_menu{\n"
"    border-image: url(:/vote/image/右箭头.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_menu:hover\n"
"{\n"
"    border-image: url(:/vote/image/右箭头-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_menu:pressed\n"
"{\n"
"    border-image: url(:/vote/image/右箭头-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_menu.setText("")
        self.pushButton_menu.setObjectName("pushButton_menu")
        self.gridLayout_2.addWidget(self.pushButton_menu, 0, 2, 1, 1)
        self.pushButton_add_font_size = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_font_size.sizePolicy().hasHeightForWidth())
        self.pushButton_add_font_size.setSizePolicy(sizePolicy)
        self.pushButton_add_font_size.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_add_font_size.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_add_font_size.setStyleSheet("#pushButton_add_font_size{\n"
"    border-image: url(:/vote/image/font_size_up.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_add_font_size:hover\n"
"{\n"
"    border-image: url(:/vote/image/font_size_up_press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_add_font_size:pressed\n"
"{\n"
"    border-image: url(:/vote/image/font_size_up_press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_add_font_size.setText("")
        self.pushButton_add_font_size.setObjectName("pushButton_add_font_size")
        self.gridLayout_2.addWidget(self.pushButton_add_font_size, 11, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.widget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 13, 2, 1, 1)
        self.pushButton_delLine = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_delLine.sizePolicy().hasHeightForWidth())
        self.pushButton_delLine.setSizePolicy(sizePolicy)
        self.pushButton_delLine.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_delLine.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_delLine.setStyleSheet("#pushButton_delLine{\n"
"    border-image: url(:/vote/image/减号.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_delLine:hover\n"
"{\n"
"    border-image: url(:/vote/image/减号-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_delLine:pressed\n"
"{\n"
"    border-image: url(:/vote/image/减号-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_delLine.setText("")
        self.pushButton_delLine.setObjectName("pushButton_delLine")
        self.gridLayout_2.addWidget(self.pushButton_delLine, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 40))
        self.label_6.setMaximumSize(QtCore.QSize(30, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 2, 1, 1)
        self.pushButton_head_show = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_head_show.sizePolicy().hasHeightForWidth())
        self.pushButton_head_show.setSizePolicy(sizePolicy)
        self.pushButton_head_show.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_head_show.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_head_show.setStyleSheet("#pushButton_head_show{\n"
"    border-image: url(:/vote/image/表头显示.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_head_show:hover\n"
"{\n"
"    border-image: url(:/vote/image/表头显示-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_head_show:pressed\n"
"{\n"
"    border-image: url(:/vote/image/表头显示-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_head_show.setText("")
        self.pushButton_head_show.setObjectName("pushButton_head_show")
        self.gridLayout_2.addWidget(self.pushButton_head_show, 14, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(30, 40))
        self.label_5.setMaximumSize(QtCore.QSize(30, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 10, 2, 1, 1)
        self.pushButton_addLine = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addLine.sizePolicy().hasHeightForWidth())
        self.pushButton_addLine.setSizePolicy(sizePolicy)
        self.pushButton_addLine.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_addLine.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_addLine.setStyleSheet("#pushButton_addLine{\n"
"    \n"
"    \n"
"    border-image: url(:/vote/image/加.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_addLine:hover\n"
"{\n"
"    \n"
"    \n"
"    border-image: url(:/vote/image/加-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_addLine:pressed\n"
"{\n"
"    border-image: url(:/vote/image/加-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_addLine.setText("")
        self.pushButton_addLine.setObjectName("pushButton_addLine")
        self.gridLayout_2.addWidget(self.pushButton_addLine, 4, 2, 1, 1)
        self.pushButton_head_hide = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_head_hide.sizePolicy().hasHeightForWidth())
        self.pushButton_head_hide.setSizePolicy(sizePolicy)
        self.pushButton_head_hide.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_head_hide.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_head_hide.setStyleSheet("#pushButton_head_hide{\n"
"    border-image: url(:/vote/image/表头隐藏.png);\n"
"    border-width: 5px;\n"
"}\n"
"#pushButton_head_hide:hover\n"
"{\n"
"    border-image: url(:/vote/image/表头隐藏-press.png);\n"
"    border-width: 0px;\n"
"}\n"
" \n"
"#pushButton_head_hide:pressed\n"
"{\n"
"    border-image: url(:/vote/image/表头隐藏-press.png);\n"
"    border-width: 3px;\n"
"\n"
"}\n"
" ")
        self.pushButton_head_hide.setText("")
        self.pushButton_head_hide.setObjectName("pushButton_head_hide")
        self.gridLayout_2.addWidget(self.pushButton_head_hide, 15, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(19)
        self.tableWidget.setFont(font)
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget.setStyleSheet("#tableWidget{border:None;\n"
"border-image:none;\n"
"background-color:transparent;}\n"
"\n"
"\n"
"\n"
"/*表头*/\n"
"QHeaderView::section{\n"
"text-align:center;\n"
"padding:3px;\n"
"margin:0px;\n"
"border:1px solid gray;\n"
"border-left-width:0;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar:vertical{ \n"
"    width:12px;  \n"
"    border-style:flat;\n"
"    border-radius: 4px;\n"
"    border:0px;\n"
"    background: #3c90ff;\n"
"} \n"
"QScrollBar::handle:vertical{ \n"
"    background:#3c90ff;\n"
"    border-radius: 4px;\n"
"    width:8px; \n"
"    min-height:91px; \n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::handle:vertical::hover{ \n"
"    background: #4039ff;\n"
"    border-radius: 4px;\n"
"    width:8px; \n"
"}\n"
"QScrollBar::handle:vertical::pressed{ \n"
"    background: #4039ff;\n"
"    border-radius:4px;\n"
"    width:8px; \n"
"}\n"
"QScrollBar::sub-page:vertical {\n"
"    background: #ffffff;\n"
"border-style:flat;\n"
"}\n"
"QScrollBar::add-page:vertical {\n"
"   background: #ffffff;\n"
"border-style:flat;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"   background: #ffffff;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   background:#ffffff;\n"
"}\n"
"QScrollBar:horizontal{ \n"
"    height:12px;  \n"
"    border-style:flat;\n"
"    border-radius: 4px;\n"
"    border:0px;\n"
"background: #3c90ff;\n"
"} \n"
"QScrollBar::handle:horizontal{ \n"
"    background: #3c90ff;\n"
"    border-radius: 4px;\n"
"    height:8px; \n"
"    min-width:91px; \n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::handle:horizontal::hover{ \n"
"    background: #4039ff;\n"
"    border-radius: 4px;\n"
"    height:8px; \n"
"}\n"
"QScrollBar::handle:horizontal::pressed{ \n"
"    background:  #4039ff;\n"
"    border-radius:4px;\n"
"    height:8px; \n"
"}\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: #ffffff;\n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::add-page:horizontal {\n"
"   background: #ffffff;\n"
"    border-style:flat;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   background: #19191A;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"   background: #ffffff;\n"
"}\n"
"\n"
"")
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 16, 1)
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.pushButton_split = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_split.setGeometry(QtCore.QRect(40, 250, 231, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_split.sizePolicy().hasHeightForWidth())
        self.pushButton_split.setSizePolicy(sizePolicy)
        self.pushButton_split.setStyleSheet("\n"
"#pushButton_split\n"
"{\n"
"    color: white;\n"
"    background-color:  #6973ff;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"    font: 14pt \"黑体\";\n"
"\n"
"}\n"
"#pushButton_split:hover\n"
"{\n"
"    color: white;\n"
"    background-color: #3f31ff;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"}\n"
" \n"
"#pushButton_split:pressed\n"
"{\n"
"    color: white;\n"
"    background-color:  #3f31ff;\n"
"    border-width: 5px;\n"
"    border-radius: 15px;\n"
"    font: 12pt \"黑体\";\n"
"}\n"
" ")
        self.pushButton_split.setObjectName("pushButton_split")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 440, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_combine = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_combine.setGeometry(QtCore.QRect(40, 200, 231, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_combine.sizePolicy().hasHeightForWidth())
        self.pushButton_combine.setSizePolicy(sizePolicy)
        self.pushButton_combine.setStyleSheet("#pushButton_combine\n"
"{\n"
"    color: white;\n"
"    background-color:  #6973ff;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"    font: 14pt \"黑体\";\n"
"\n"
"}\n"
"#pushButton_combine:hover\n"
"{\n"
"    color: white;\n"
"    background-color: #3f31ff;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"}\n"
" \n"
"#pushButton_combine:pressed\n"
"{\n"
"    color: white;\n"
"    background-color:  #3f31ff;\n"
"    border-width: 5px;\n"
"    border-radius: 15px;\n"
"    font: 12pt \"黑体\";\n"
"}\n"
" ")
        self.pushButton_combine.setCheckable(False)
        self.pushButton_combine.setChecked(False)
        self.pushButton_combine.setObjectName("pushButton_combine")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setEnabled(True)
        self.doubleSpinBox.setGeometry(QtCore.QRect(30, 480, 191, 31))
        self.doubleSpinBox.setStyleSheet("/*QSpinBox*/\n"
"QDoubleSpinBox {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgb(221, 221, 221) ;\n"
"border-radius:10px;\n"
"font-size:18px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button {\n"
"    border-image: url(:/vote/image/arrow-up.png);\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button {\n"
"    border-image: url(:/vote/image/arrow-down-filling.png);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:pressed {\n"
"margin-top:3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed {\n"
"margin-bottom:3px;\n"
"}\n"
"")
        self.doubleSpinBox.setProperty("value", 19.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(30, 310, 241, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox)
        self.fontComboBox.setEnabled(True)
        self.fontComboBox.setGeometry(QtCore.QRect(30, 390, 221, 31))
        self.fontComboBox.setStyleSheet("QFontComboBox::down-arrow\n"
" {\n"
"    border-image: url(:/vote/image/arrow-down-filling.png);\n"
"\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item { \n"
"min-height: 34px;\n"
" }\n"
"QFontComboBox::drop-down {\n"
"border:0px solid gray;width: 30px;\n"
"}\n"
"QFontComboBox{\n"
"font-size:18px;\n"
"border:1px solid rgb(221, 221, 221) ;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"")
        self.fontComboBox.setObjectName("fontComboBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 350, 241, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_row = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_row.setGeometry(QtCore.QRect(150, 50, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_row.sizePolicy().hasHeightForWidth())
        self.lineEdit_row.setSizePolicy(sizePolicy)
        self.lineEdit_row.setStyleSheet("#lineEdit_row {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgb(221, 221, 221) ;\n"
"border-radius:10px;\n"
"font-size:18px;\n"
"\n"
"}")
        self.lineEdit_row.setObjectName("lineEdit_row")
        self.lineEdit_column = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_column.setGeometry(QtCore.QRect(150, 100, 121, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_column.sizePolicy().hasHeightForWidth())
        self.lineEdit_column.setSizePolicy(sizePolicy)
        self.lineEdit_column.setStyleSheet("#lineEdit_column {\n"
"padding-right: 15px; /* make room for the arrows */\n"
"border:1px solid rgb(221, 221, 221) ;\n"
"border-radius:10px;\n"
"font-size:18px;\n"
"}")
        self.lineEdit_column.setText("")
        self.lineEdit_column.setObjectName("lineEdit_column")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 101, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(40, 150, 231, 31))
        self.pushButton.setStyleSheet("#pushButton\n"
"{\n"
"    color: white;\n"
"    background-color:  #6973ff;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"    font: 14pt \"黑体\";\n"
"\n"
"}\n"
"#pushButton:hover\n"
"{\n"
"    color: white;\n"
"    background-color: #3f31ff;\n"
"    border-width: 3px;\n"
"    border-radius: 15px;\n"
"}\n"
" \n"
"#pushButton:pressed\n"
"{\n"
"    color: white;\n"
"    background-color:  #3f31ff;\n"
"    border-width: 5px;\n"
"    border-radius: 15px;\n"
"    font: 12pt \"黑体\";\n"
"}\n"
" ")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.groupBox, 0, 3, 16, 1)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "计票程序"))
        self.pushButton_windowStatus.setToolTip(_translate("Form", "<html><head/><body><p>满屏/正常大小显示</p></body></html>"))
        self.pushButton_down_font_size.setToolTip(_translate("Form", "<html><head/><body><p>减小选中字体大小</p></body></html>"))
        self.pushButton_delCol.setToolTip(_translate("Form", "<html><head/><body><p>删除一列</p></body></html>"))
        self.pushButton_addCol.setToolTip(_translate("Form", "<html><head/><body><p>添加一列</p></body></html>"))
        self.pushButton_menu.setToolTip(_translate("Form", "<html><head/><body><p>显示/隐藏右侧功能区</p></body></html>"))
        self.pushButton_add_font_size.setToolTip(_translate("Form", "<html><head/><body><p>增加选中字体大小</p></body></html>"))
        self.pushButton_delLine.setToolTip(_translate("Form", "<html><head/><body><p>删除一行</p></body></html>"))
        self.label_6.setText(_translate("Form", "列"))
        self.pushButton_head_show.setToolTip(_translate("Form", "<html><head/><body><p>显示表头及网格</p></body></html>"))
        self.label_5.setText(_translate("Form", "行"))
        self.pushButton_addLine.setToolTip(_translate("Form", "<html><head/><body><p>添加一行</p></body></html>"))
        self.pushButton_head_hide.setToolTip(_translate("Form", "<html><head/><body><p>隐藏表头及网格</p></body></html>"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("Form", "功能设置区"))
        self.pushButton_split.setText(_translate("Form", "清空单元格"))
        self.label.setText(_translate("Form", "调整选中单元格字体大小："))
        self.pushButton_combine.setText(_translate("Form", "重置表格"))
        self.label_2.setText(_translate("Form", "调整选中单元格字体："))
        self.label_3.setText(_translate("Form", "设置行数："))
        self.label_4.setText(_translate("Form", "设置列数："))
        self.pushButton.setText(_translate("Form", "确   定"))
# import voteImageSource_rc
